### ISSUE TITLE
[BUG]  Invalid syntax error when determining python versions

### ISSUE THREAD

**Issue by nelson-liu** [conda-incubator/grayskull#201]
**Describe the bug**

When running `grayskull pypi codalab`, I get:

```
#### Initializing recipe for codalab (pypi) ####

Recovering metadata from pypi...
Starting the download of the sdist package codalab-0.5.26.tar.gz
codalab-0.5.26.tar.gz 100% Time:  0:00:00   1.5 MiB/s|###############################################|
Recovering information from setup.py
Executing injected distutils...
Recovering metadata from setup.cfg
Checking >> argcomplete 100% |################################################|[Elapsed Time: 0:00:13]
Recovering license info from spdx.org ...
Recovering license information from github...
Recovering license info from repository...
Cloning into '/tmp/gs-clone-repo-fbayfp9n'...
fatal: Remote branch 0.5.26 not found in upstream origin
Recovering license info from repository...
Cloning into '/tmp/gs-clone-repo-pvzmwh0v'...
remote: Enumerating objects: 200, done.
remote: Counting objects: 100% (200/200), done.
remote: Compressing objects: 100% (143/143), done.
remote: Total 27944 (delta 104), reused 107 (delta 56), pack-reused 27744
Receiving objects: 100% (27944/27944), 20.07 MiB | 709.00 KiB/s, done.
Resolving deltas: 100% (21314/21314), done.
Note: switching to '115220ec988617f12d6c1efa13d95be6b7cd6543'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

License type: Apache-2.0
License file: LICENSE.txt
Traceback (most recent call last):
  File "/home/nfliu/miniconda3/envs/condaforge/bin/grayskull", line 10, in <module>
    sys.exit(main())
  File "/home/nfliu/miniconda3/envs/condaforge/lib/python3.7/site-packages/grayskull/__main__.py", line 126, in main
    is_strict_cf=args.is_strict_conda_forge,
  File "/home/nfliu/miniconda3/envs/condaforge/lib/python3.7/site-packages/grayskull/base/factory.py", line 23, in create_recipe
    name, version, **kwargs
  File "/home/nfliu/miniconda3/envs/condaforge/lib/python3.7/site-packages/grayskull/pypi/pypi.py", line 58, in __init__
    super(PyPi, self).__init__(name=name, version=str(version) if version else None)
  File "/home/nfliu/miniconda3/envs/condaforge/lib/python3.7/site-packages/grayskull/base/base_recipe.py", line 58, in __init__
    self.update_all_recipe()
  File "/home/nfliu/miniconda3/envs/condaforge/lib/python3.7/site-packages/grayskull/base/base_recipe.py", line 114, in update_all_recipe
    self.refresh_section(section)
  File "/home/nfliu/miniconda3/envs/condaforge/lib/python3.7/site-packages/grayskull/pypi/pypi.py", line 525, in refresh_section
    metadata = self._get_metadata()
  File "/home/nfliu/miniconda3/envs/condaforge/lib/python3.7/site-packages/grayskull/pypi/pypi.py", line 566, in _get_metadata
    all_requirements = self._extract_requirements(metadata)
  File "/home/nfliu/miniconda3/envs/condaforge/lib/python3.7/site-packages/grayskull/pypi/pypi.py", line 798, in _extract_requirements
    metadata, is_strict_cf=self._is_strict_cf
  File "/home/nfliu/miniconda3/envs/condaforge/lib/python3.7/site-packages/grayskull/pypi/pypi.py", line 1045, in py_version_to_limit_python
    pypi_metadata, is_selector=False, is_strict_cf=is_strict_cf
  File "/home/nfliu/miniconda3/envs/condaforge/lib/python3.7/site-packages/grayskull/pypi/pypi.py", line 994, in _generic_py_ver_to
    req_python, is_strict_cf=is_strict_cf
  File "/home/nfliu/miniconda3/envs/condaforge/lib/python3.7/site-packages/grayskull/pypi/pypi.py", line 1082, in _get_py_version_available
    f"sup_py {op} PyVer(int({major}), int({minor}))"
  File "<string>", line 1
    sup_py = PyVer(int(3), int(6))
           ^
SyntaxError: invalid syntax
```

**To Reproduce**
`grayskull pypi codalab`

**Environment:**

```
$ conda list
# packages in environment at /home/nfliu/miniconda3/envs/condaforge:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
alabaster                 0.7.12                     py_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
brotlipy                  0.7.0           py37hb5d75c8_1001    conda-forge
c-ares                    1.16.1               h516909a_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37he5f6b98_2    conda-forge
cffi                      1.14.3           py37he30daa8_0
chardet                   3.0.4           py37he5f6b98_1008    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cryptography              3.2.1            py37hc72a4ac_0    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
docutils                  0.16             py37he5f6b98_2    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
git                       2.29.2          pl5262h78be0e9_0    conda-forge
grayskull                 0.8.3                      py_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
krb5                      1.17.1               hfafb76e_3    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7
libcurl                   7.71.1               hcdd3856_8    conda-forge
libedit                   3.1.20191231         h14c3975_1
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libiconv                  1.16                 h516909a_0    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0
markupsafe                1.1.1            py37hb5d75c8_2    conda-forge
ncurses                   6.2                  he6710b0_1
openssl                   1.1.1h               h516909a_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
pip                       20.2.4           py37h06a4308_0
progressbar2              3.53.1             pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.2                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysocks                   1.7.1            py37he5f6b98_2    conda-forge
python                    3.7.9                h7579374_0
python-utils              2.4.0                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.4             pyhd8ed1ab_0    conda-forge
rapidfuzz                 0.12.5           py37h3340039_0    conda-forge
readline                  8.0                  h7b6447c_0
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
ruamel.yaml               0.16.12          py37h8f50634_1    conda-forge
ruamel.yaml.clib          0.2.2            py37h8f50634_1    conda-forge
ruamel.yaml.jinja2        0.2.4                      py_1    conda-forge
setuptools                50.3.0           py37h06a4308_1
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sphinx                    3.3.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
sqlite                    3.33.0               h62c20be_0
stdlib-list               0.7.0                      py_2    conda-forge
tk                        8.6.10               hbc83047_0
urllib3                   1.25.11                    py_0    conda-forge
wheel                     0.35.1                     py_0
xz                        5.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3
```

```
$ pip list
Package                       Version
----------------------------- -------------------
alabaster                     0.7.12
Babel                         2.8.0
brotlipy                      0.7.0
certifi                       2020.6.20
cffi                          1.14.3
chardet                       3.0.4
colorama                      0.4.4
cryptography                  3.2.1
docutils                      0.16
grayskull                     0.8.3
idna                          2.10
imagesize                     1.2.0
Jinja2                        2.11.2
MarkupSafe                    1.1.1
packaging                     20.4
pip                           20.2.4
progressbar2                  3.53.1
pycparser                     2.20
Pygments                      2.7.2
pyOpenSSL                     19.1.0
pyparsing                     2.4.7
PySocks                       1.7.1
python-utils                  2.4.0
pytz                          2020.4
rapidfuzz                     0.12.5
requests                      2.24.0
ruamel.yaml                   0.16.12
ruamel.yaml.clib              0.2.2
ruamel.yaml.jinja2            0.2.4
setuptools                    50.3.0.post20201103
six                           1.15.0
snowballstemmer               2.0.0
Sphinx                        3.3.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
stdlib-list                   0.7.0
urllib3                       1.25.11
wheel                         0.35.1
```

```
$ grayskull --version
0.8.3
```

**Comment by nelson-liu** [comment]
Maybe this is because it has `python_requires='~=3.6',`

**Comment by marcelotrevisani** [comment]
> Maybe this is because it has `python_requires='~=3.6',`

Indeed! It needs to be fixed. Thanks for reporting it! :)
