### ISSUE TITLE
[BUG] Illegal hardware request on fresh grayskull 

### ISSUE THREAD

**Issue by lc5415** [conda-incubator/grayskull#203]
**Describe the bug**
I am trying to play with grayksull to see if fits my use case. I've installed it from `pip` and run `grayskull pypi pandas` and gotten a long stack of errors and a message saying `illegal hardware request`

**To Reproduce**
1. Install grayskull using pip in core macbook environment (no conda env, no venv): `pip install grayskull`
2. Run `python3 -m pip install grayskull`

**Expected behavior**
Pandas recipe to be created.

**Outputs**

<details> 
<summary>Click to expand error stack trace</summary>

```python
#### Initializing recipe for pandas (pypi) ####

Recovering metadata from pypi...
Starting the download of the sdist package pandas-1.1.4.tar.gz
pandas-1.1.4.tar.gz 100% Time:  0:00:02   1.6 MiB/s|#########################################################################|
Recovering information from setup.py
Executing injected distutils...
Traceback (most recent call last):
  File "/Users/luischavesrodriguez/Library/Python/3.7/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'
ERROR:It was not possible to install setuptools.
Command: pip install setuptools --target=/var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-annpkgbe.
Error: Command '['pip', 'install', 'setuptools', '--target=/var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-annpkgbe']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/Users/luischavesrodriguez/Library/Python/3.7/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'
ERROR:It was not possible to install setuptools.
Command: pip install setuptools --target=/var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-annpkgbe.
Error: Command '['pip', 'install', 'setuptools', '--target=/var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-annpkgbe']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/Users/luischavesrodriguez/Library/Python/3.7/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'
ERROR:It was not possible to install cython.
Command: pip install cython --target=/var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-annpkgbe.
Error: Command '['pip', 'install', 'cython', '--target=/var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-annpkgbe']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/Users/luischavesrodriguez/Library/Python/3.7/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'
ERROR:It was not possible to install numpy.
Command: pip install numpy --target=/var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-annpkgbe.
Error: Command '['pip', 'install', 'numpy', '--target=/var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-annpkgbe']' returned non-zero exit status 1.
Recovering metadata from setup.cfg
No data was recovered from setup.py. Forcing to execute the setup.py as script
Traceback (most recent call last):
  File "/Users/luischavesrodriguez/Library/Python/3.7/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'
ERROR:It was not possible to install setuptools.
Command: pip install setuptools --target=/var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-cn_lbbxw.
Error: Command '['pip', 'install', 'setuptools', '--target=/var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-cn_lbbxw']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/Users/luischavesrodriguez/Library/Python/3.7/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'
ERROR:It was not possible to install setuptools.
Command: pip install setuptools --target=/var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-cn_lbbxw.
Error: Command '['pip', 'install', 'setuptools', '--target=/var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-cn_lbbxw']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/Users/luischavesrodriguez/Library/Python/3.7/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'
ERROR:It was not possible to install cython.
Command: pip install cython --target=/var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-cn_lbbxw.
Error: Command '['pip', 'install', 'cython', '--target=/var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-cn_lbbxw']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/Users/luischavesrodriguez/Library/Python/3.7/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'
ERROR:It was not possible to install numpy.
Command: pip install numpy --target=/var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-cn_lbbxw.
Error: Command '['pip', 'install', 'numpy', '--target=/var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-cn_lbbxw']' returned non-zero exit status 1.
Recovering metadata from setup.cfg
Checking >> numpy 100% |##############################################################################|[Elapsed Time: 0:00:01]
Recovering license info from spdx.org ...
[1]    6161 illegal hardware instruction  grayskull pypi pandas
```
</details>

**Environment:**
 ~- conda list~ <-- None, using core python

<details> 
<summary>  python3 -m pip list </summary>
```
Package            Version   Location
------------------ --------- --------------------------------------------------------------
appdirs            1.4.4
astroid            2.4.2
attrs              20.2.0
bleach             3.2.1
certifi            2020.6.20
chardet            3.0.4
colorama           0.4.3
distlib            0.3.1
docutils           0.16
filelock           3.0.12
flake8             3.8.4
grayskull          0.8.3
idna               2.10
iniconfig          1.0.1
isort              5.5.4
keyring            21.4.0
lazy-object-proxy  1.4.3
mccabe             0.6.1
packaging          20.4
pip                20.1.1
pkginfo            1.5.0.1
pluggy             0.13.1
progressbar2       3.53.1
py                 1.9.0
pycodestyle        2.6.0
pyflakes           2.2.0
Pygments           2.7.1
pylint             2.6.0
pyparsing          2.4.7
pytest             6.1.1
python-utils       2.4.0
rapidfuzz          0.13.3
readme-renderer    26.0
requests           2.24.0
requests-toolbelt  0.9.1
rfc3986            1.4.0
ruamel.yaml        0.16.12
ruamel.yaml.clib   0.2.2
ruamel.yaml.jinja2 0.2.4
setuptools         50.3.0
six                1.15.0
stdlib-list        0.8.0
toml               0.10.1
tqdm               4.50.0
twine              3.2.0
urllib3            1.25.10
virtualenv         20.0.33
webencodings       0.5.1
wheel              0.35.1
wrapt              1.12.1
```
</details>
 - grayskull --version: **0.8.3**

**Comment by marcelotrevisani** [comment]
I suspect what might be causing this error
I created this PR and it should cover this specific case
https://github.com/conda-incubator/grayskull/pull/205

**Comment by lc5415** [comment]
That was fast! I will clone that branch and test it out right away 👍

**Comment by marcelotrevisani** [comment]
> That was fast! I will clone that branch and test it out right away

Thanks! :)
Please let me know if it fix it

**Comment by lc5415** [comment]
Still getting the same error unfortunately, and also a bunch of warnings that I do not quite understand:
<details>
<summary> Error stack </summary>

```python
#### Initializing recipe for pandas (pypi) ####

Recovering metadata from pypi...
Starting the download of the sdist package pandas-1.1.4.tar.gz
pandas-1.1.4.tar.gz 100% Time:  0:00:02   2.1 MiB/s|#########################################################################|
Recovering information from setup.py
Executing injected distutils...
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-t0a2mxri/setuptools-50.3.2.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-t0a2mxri/easy_install.py already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-t0a2mxri/__pycache__ already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-t0a2mxri/distutils-precedence.pth already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-t0a2mxri/setuptools already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-t0a2mxri/pkg_resources already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-t0a2mxri/_distutils_hack already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-t0a2mxri/bin already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-t0a2mxri/__pycache__ already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-t0a2mxri/bin already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-t0a2mxri/bin already exists. Specify --upgrade to force replacement.
Recovering metadata from setup.cfg
No data was recovered from setup.py. Forcing to execute the setup.py as script
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-8fzk9i2g/setuptools-50.3.2.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-8fzk9i2g/easy_install.py already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-8fzk9i2g/__pycache__ already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-8fzk9i2g/distutils-precedence.pth already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-8fzk9i2g/setuptools already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-8fzk9i2g/pkg_resources already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-8fzk9i2g/_distutils_hack already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-8fzk9i2g/bin already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-8fzk9i2g/__pycache__ already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-8fzk9i2g/bin already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-8fzk9i2g/bin already exists. Specify --upgrade to force replacement.
Recovering metadata from setup.cfg
Checking >> numpy 100% |##############################################################################|[Elapsed Time: 0:00:01]
Recovering license info from spdx.org ...
[1]    8173 illegal hardware instruction  grayskull pypi pandas
```

</details>

<details>
<summary> Steps to reproduce </summary>

```sh
git clone https://github.com/conda-incubator/grayskull.git
cd grayskull
git pull origin invoke-same-python
python3 -m pip install -e .
grayskull pypi pandas
```

</details>

**Comment by marcelotrevisani** [comment]
Could you please tell me what is your architecture and OS?

**Comment by marcelotrevisani** [comment]
I suspect that is something related to the fuzzy module which is doing the comparisons, but I cannot reproduce this error
However, I can add a ``try catch`` on the fuzzy part in case of a exception like that and it will not kill grayskull, with that grayskull will be able to generate the recipe. Just the license will not be the right one.

**Comment by lc5415** [comment]
It's a macBook Pro 2015 with the following OS:
ProductName: Mac OS X
ProductVersion: 10.15.7
BuildVersion:	19H15

And by the way, when I've created a virtualenv I've had no problem using the tool. Most of the time I work in environments and most people do/should anyway

**Comment by marcelotrevisani** [comment]
> It's a macBook Pro 2015 with the following OS:
> ProductName: Mac OS X
> ProductVersion: 10.15.7
> BuildVersion: 19H15
> 
> And by the way, when I've created a virtualenv I've had no problem using the tool. Most of the time I work in environments and most people do/should anyway. I don't think it's a big problem

Oh, I see, that also gives me some hints what might be happening, thanks! I am pretty sure that is something related to the ``rapidfuzz``, I will at least make sure this problem does not kill grayskull and it continues to generate the recipe

**Comment by marcelotrevisani** [comment]
Well.. at least the CI reproduced it
https://pipelines.actions.githubusercontent.com/mT3fTi8tkI7eCWY7kY7pcRdRx92fCvBT7tGuDtb00jPlIBZL0O/_apis/pipelines/1/runs/576/signedlogcontent/4?urlExpires=2020-11-22T21%3A28%3A59.0945583Z&urlSigningMethod=HMACV1&urlSignature=VTMdxiJy92%2FM8AeK7zon7KyfWAKxgyG41T3HghvM4gk%3D

**Comment by marcelotrevisani** [comment]
As I suspected it is something related to the ``rapidfuzz`` dependency doing the fuzzy comparison for the license.
If you do ``python3 -m pip install "rapidfuzz<0.13.0"`` that will solve the problem

**Comment by marcelotrevisani** [comment]
After I integrate the #205 I will generate a new version fixing this problem

**Comment by marcelotrevisani** [comment]
Version ``0.8.4`` is already on ``pypi``
https://pypi.org/project/grayskull/

**Comment by lc5415** [comment]
I did no longer got the "Illegal hardware request" with version 0.8.4! Thanks for the quick fix @marcelotrevisani 

<details>
<summary> I still got a stack of warnings, which I thought were gonna go if I upgraded but they didn't! </summary>

```python
#### Initializing recipe for pandas (pypi) ####

Recovering metadata from pypi...
Starting the download of the sdist package pandas-1.1.4.tar.gz
pandas-1.1.4.tar.gz 100% Time:  0:00:02   1.8 MiB/s|#########################################################################|
Recovering information from setup.py
Executing injected distutils...
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-li6vne_m/__pycache__ already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-li6vne_m/bin already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-li6vne_m/setuptools-50.3.2.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-li6vne_m/easy_install.py already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-li6vne_m/__pycache__ already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-li6vne_m/distutils-precedence.pth already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-li6vne_m/setuptools already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-li6vne_m/pkg_resources already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-li6vne_m/_distutils_hack already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-li6vne_m/bin already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-li6vne_m/bin already exists. Specify --upgrade to force replacement.
Recovering metadata from setup.cfg
No data was recovered from setup.py. Forcing to execute the setup.py as script
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-qkz_7pqk/__pycache__ already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-qkz_7pqk/bin already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-qkz_7pqk/setuptools-50.3.2.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-qkz_7pqk/easy_install.py already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-qkz_7pqk/__pycache__ already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-qkz_7pqk/distutils-precedence.pth already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-qkz_7pqk/setuptools already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-qkz_7pqk/pkg_resources already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-qkz_7pqk/_distutils_hack already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-qkz_7pqk/bin already exists. Specify --upgrade to force replacement.
WARNING: Target directory /var/folders/h4/30q_k34n2y77hfr_3_dq5q_40000gn/T/pip-dir-qkz_7pqk/bin already exists. Specify --upgrade to force replacement.
Recovering metadata from setup.cfg
Checking >> numpy 100% |##############################################################################|[Elapsed Time: 0:00:01]
Recovering license info from spdx.org ...
Matching license file with database from Grayskull...
License type: BSD-3-Clause
License file: LICENSE
Host requirements:
  - cython
  - numpy
  - pip
  - python >=3.6

Run requirements:
  - numpy >=1.15.4
  - python >=3.6
  - python-dateutil >=2.7.3
  - pytz >=2017.2

RED: Missing packages
GREEN: Packages available on conda-forge
Maintainers:
   - LuisF3

#### Recipe generated on /Users/luischavesrodriguez for pandas ####
```

</details>
