### ISSUE TITLE
[BUG] AttributeError when creating recipe

### ISSUE THREAD

**Issue by BastianZim** [conda-incubator/grayskull#207]
**Describe the bug**
When running `grayskull pypi pysentiment2` I received an attribute error.

**To Reproduce**
1. Execute `grayskull pypi pysentiment2`

**Expected behavior**
A recipe should be successfully created.

**Outputs**

```zsh

#### Initializing recipe for pysentiment2 (pypi) ####

Recovering metadata from pypi...
Starting the download of the sdist package pysentiment2-0.1.1.tar.gz
pysentiment2-0.1.1.tar.gz 100% Time:  0:00:01 895.8 KiB/s|##########################################################################################################################|
Recovering information from setup.py
Executing injected distutils...
Recovering metadata from setup.cfg
Checking >> nltk 100% |######################################################################################################################################|[Elapsed Time: 0:00:00]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/grayskull-create/bin/grayskull", line 10, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/grayskull-create/lib/python3.8/site-packages/grayskull/__main__.py", line 121, in main
    recipe = GrayskullFactory.create_recipe(
  File "/opt/anaconda3/envs/grayskull-create/lib/python3.8/site-packages/grayskull/base/factory.py", line 22, in create_recipe
    return GrayskullFactory.REGISTERED_CLASS[repo_type.lower()](
  File "/opt/anaconda3/envs/grayskull-create/lib/python3.8/site-packages/grayskull/pypi/pypi.py", line 58, in __init__
    super(PyPi, self).__init__(name=name, version=str(version) if version else None)
  File "/opt/anaconda3/envs/grayskull-create/lib/python3.8/site-packages/grayskull/base/base_recipe.py", line 58, in __init__
    self.update_all_recipe()
  File "/opt/anaconda3/envs/grayskull-create/lib/python3.8/site-packages/grayskull/base/base_recipe.py", line 114, in update_all_recipe
    self.refresh_section(section)
  File "/opt/anaconda3/envs/grayskull-create/lib/python3.8/site-packages/grayskull/pypi/pypi.py", line 534, in refresh_section
    metadata = self._get_metadata()
  File "/opt/anaconda3/envs/grayskull-create/lib/python3.8/site-packages/grayskull/pypi/pypi.py", line 557, in _get_metadata
    metadata = PyPi._merge_pypi_sdist_metadata(pypi_metadata, sdist_metadata)
  File "/opt/anaconda3/envs/grayskull-create/lib/python3.8/site-packages/grayskull/pypi/pypi.py", line 418, in _merge_pypi_sdist_metadata
    "entry_points": PyPi._get_entry_points_from_sdist(sdist_metadata),
  File "/opt/anaconda3/envs/grayskull-create/lib/python3.8/site-packages/grayskull/pypi/pypi.py", line 477, in _get_entry_points_from_sdist
    return_entry_point.extend(entry_point.split("\n"))
AttributeError: 'list' object has no attribute 'split'

```

**Environment:**
 - conda list

```zsh
# packages in environment at /opt/anaconda3/envs/grayskull-create:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
brotlipy                  0.7.0           py38h94c058a_1001    conda-forge
c-ares                    1.17.1               hc929b4f_0    conda-forge
ca-certificates           2020.12.5            h033912b_0    conda-forge
certifi                   2020.12.5        py38h50d1736_0    conda-forge
cffi                      1.14.4           py38h979bc6b_1    conda-forge
chardet                   3.0.4           py38h5347e94_1008    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cryptography              3.3.1            py38h6b4ec92_0    conda-forge
curl                      7.71.1               hcb81553_8    conda-forge
docutils                  0.16             py38h5347e94_2    conda-forge
expat                     2.2.9                h4a8c4bd_2    conda-forge
gettext                   0.19.8.1          h7937167_1005    conda-forge
git                       2.29.2          pl5320h422953c_1    conda-forge
grayskull                 0.8.4              pyhd8ed1ab_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
krb5                      1.17.1               h14dd6a4_2    conda-forge
libcurl                   7.71.1               h9bf37e3_8    conda-forge
libcxx                    10.0.0                        1  
libedit                   3.1.20191231         h1de35cc_1  
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  hb1e8313_2  
libiconv                  1.16                 haf1e3a3_0    conda-forge
libnghttp2                1.41.0               h8a08a2b_1    conda-forge
libssh2                   1.9.0                h8a08a2b_5    conda-forge
markupsafe                1.1.1            py38h94c058a_2    conda-forge
ncurses                   6.2                  h0a44026_1  
openssl                   1.1.1i               h35c211d_0    conda-forge
packaging                 20.8               pyhd3deb0d_0    conda-forge
pcre                      8.44                 h4a8c4bd_0    conda-forge
perl                      5.32.0               hbcb3906_0    conda-forge
pip                       20.3.1           py38hecd8cb5_0  
progressbar2              3.53.1             pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysocks                   1.7.1            py38h5347e94_2    conda-forge
python                    3.8.5                h26836e1_1  
python-utils              2.4.0                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.4             pyhd8ed1ab_0    conda-forge
rapidfuzz                 0.9.1            py38h7d85814_1    conda-forge
readline                  8.0                  h1de35cc_0  
requests                  2.25.0             pyhd3deb0d_0    conda-forge
ruamel.yaml               0.16.12          py38h1130bcf_1    conda-forge
ruamel.yaml.clib          0.2.2            py38h1130bcf_1    conda-forge
ruamel.yaml.jinja2        0.2.4                      py_1    conda-forge
setuptools                51.0.0           py38hecd8cb5_2  
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sphinx                    3.3.1              pyhd8ed1ab_1    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
sqlite                    3.33.0               hffcf06c_0  
stdlib-list               0.7.0                      py_2    conda-forge
tk                        8.6.10               hb0a8c7a_0  
urllib3                   1.25.11                    py_0    conda-forge
wheel                     0.36.1             pyhd3eb1b0_0  
xz                        5.2.5                h1de35cc_0  
zlib                      1.2.11               h1de35cc_3  
```

 - pip list

```zsh
Package                       Version
----------------------------- -------------------
alabaster                     0.7.12
Babel                         2.9.0
brotlipy                      0.7.0
certifi                       2020.12.5
cffi                          1.14.4
chardet                       3.0.4
colorama                      0.4.4
cryptography                  3.3.1
docutils                      0.16
grayskull                     0.8.4
idna                          2.10
imagesize                     1.2.0
Jinja2                        2.11.2
MarkupSafe                    1.1.1
packaging                     20.8
pip                           20.3.1
progressbar2                  3.53.1
pycparser                     2.20
Pygments                      2.7.3
pyOpenSSL                     20.0.0
pyparsing                     2.4.7
PySocks                       1.7.1
python-utils                  2.4.0
pytz                          2020.4
rapidfuzz                     0.9.1
requests                      2.25.0
ruamel.yaml                   0.16.12
ruamel.yaml.clib              0.2.2
ruamel.yaml.jinja2            0.2.4
setuptools                    51.0.0.post20201207
six                           1.15.0
snowballstemmer               2.0.0
Sphinx                        3.3.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
stdlib-list                   0.7.0
urllib3                       1.25.11
wheel                         0.36.1
```

 - grayskull --version

```zsh
0.8.4
```

**Additional context**

The project I'm installing is [pysentiment2](https://pypi.org/project/pysentiment2/)

**Comment by BastianZim** [comment]
Also, thanks for creating this project and happy holidays!

**Comment by marcelotrevisani** [comment]
Hi @BastianZim , indeed, this is a bug. I believe it should not be difficult to fix. I hope in the up coming weeks I will release a new version fixing it.
Thanks for reporting it! :)

**Comment by BastianZim** [comment]
Hi @marcelotrevisani, awesome, thanks for the quick response! Should I close the issue or leave it open until then? 
Pleasure! :)

**Comment by marcelotrevisani** [comment]
> Hi @marcelotrevisani, awesome, thanks for the quick response! Should I close the issue or leave it open until then?
> Pleasure! :)

Please leave it open until then, I will close it when I fix it :)

**Comment by BastianZim** [comment]
Will do! :)
