### ISSUE TITLE
[BUG] safe_load doesn't work with meta.yaml output

### ISSUE THREAD

**Issue by sgbaird** [conda-incubator/grayskull#253]
**Describe the bug**
`yaml.safe_load` results in an error:
```ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '%' that cannot start any token
  in "meta.yaml", line 1, column 2
```

**To Reproduce**

`meta.yaml`
```yaml
{% set name = "mat_discover" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mat_discover-{{ version }}.tar.gz
  sha256: db4282b19dee8d851edc9dc1fc126aa0e670f0d55f3d4a718f8b23dd5fd273f0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - flit
  run:
    - cython
    - dill
    - elmd ==0.4.8
    - hdbscan
    - joblib
    - python-kaleido
    - matplotlib-base >=3.4.3
    - numba >=0.53.1
    - pandas
    - plotly
    - pqdm
    - psutil
    - pymatgen
    - python
    - scikit-learn
    - scipy
    - seaborn
    - tqdm
    - umap-learn

test:
  imports:
    - mat_discover
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/mat_discover/
  summary: Data-driven materials discovery based on composition.
  dev_url: https://github.com/sparks-baird/mat_discover
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sgbaird
```
```python
with open("meta.yaml", "r") as f:
    out = yaml.safe_load(f)
```

**Outputs**
```python
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\sterg\Miniconda3\envs\mat_discover\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\sterg\Miniconda3\envs\mat_discover\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\sterg\Miniconda3\envs\mat_discover\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\sterg\Miniconda3\envs\mat_discover\lib\site-packages\yaml\composer.py", line 35, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "C:\Users\sterg\Miniconda3\envs\mat_discover\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\sterg\Miniconda3\envs\mat_discover\lib\site-packages\yaml\parser.py", line 142, in parse_implicit_document_start
    if not self.check_token(DirectiveToken, DocumentStartToken,
  File "C:\Users\sterg\Miniconda3\envs\mat_discover\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\sterg\Miniconda3\envs\mat_discover\lib\site-packages\yaml\scanner.py", line 258, in fetch_more_tokens
    raise ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '%' that cannot start any token
  in "meta.yaml", line 1, column 2
```

**Environment:**
 - conda list
```python
(mat_discover) PS C:\Users\sterg\Documents\GitHub\sparks-baird\mat_discover> conda list
# packages in environment at C:\Users\sterg\Miniconda3\envs\mat_discover:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               21.1.0           py39hb82d6ee_0    conda-forge
ase                       3.22.0             pyhd8ed1ab_0    conda-forge
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge      
black                     21.9b0             pyhd8ed1ab_1    conda-forge
blas                      2.108                       mkl    conda-forge
blas-devel                3.9.0                     8_mkl    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
bounded-pool-executor     0.0.3                      py_0    sgbaird
brotlipy                  0.7.0           py39hb82d6ee_1001    conda-forge        
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
certifi                   2021.10.8        py39hcbf5309_0    conda-forge
cffi                      1.14.6           py39h0878f49_1    conda-forge
cfgv                      3.3.1              pyhd8ed1ab_0    conda-forge
cftime                    1.5.1            py39h5d4886f_0    conda-forge
chardet                   4.0.0            py39hcbf5309_1    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
click                     8.0.3            py39hcbf5309_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cryptography              35.0.0           py39hd8d06c1_0    conda-forge
cudatoolkit               11.3.1               h280eb24_9    conda-forge
curl                      7.79.1               h789b8ee_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.24                  pypi_0    pypi
dataclasses               0.8                pyhc8e2a94_3    conda-forge
debugpy                   1.4.1            py39h415ef7b_0    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.4              pyhd8ed1ab_0    conda-forge
distlib                   0.3.3              pyhd8ed1ab_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
docutils                  0.17.1           py39hcbf5309_0    conda-forge
double-conversion         3.1.5                h0e60522_2    conda-forge
editdistance-s            1.0.0            py39h2e07f2f_1    conda-forge
eigen                     3.4.0                h2d74725_0    conda-forge
elm2d                     0.4.1                    pypi_0    pypi
elmd                      0.4.8                      py_0    sgbaird
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.4.1                h39d44d4_0    conda-forge
ffmpeg                    4.3.1                ha925a31_0    conda-forge
filelock                  3.3.1              pyhd8ed1ab_0    conda-forge
flake8                    4.0.1              pyhd8ed1ab_0    conda-forge
flask                     2.0.2              pyhd8ed1ab_0    conda-forge
flit                      3.4.0              pyhd8ed1ab_0    conda-forge
flit-core                 3.4.0              pyhd8ed1ab_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
future                    0.18.2           py39hcbf5309_3    conda-forge
git                       2.33.1               h57928b3_0    conda-forge
gl2ps                     1.4.2                h0597ee9_0    conda-forge
glew                      2.1.0                h39d44d4_2    conda-forge
grayskull                 0.9.1              pyhd8ed1ab_0    conda-forge
hdbscan                   0.8.27           py39h5d4886f_0    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge      
icu                       68.1                 h0e60522_0    conda-forge
identify                  2.3.1              pyhd8ed1ab_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        4.8.1            py39hcbf5309_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2021.4.0          h57928b3_3556    conda-forge
ipykernel                 6.4.2            py39h832f523_0    conda-forge
ipython                   7.28.0           py39h832f523_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
itsdangerous              2.0.1              pyhd8ed1ab_0    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jedi                      0.18.0           py39hcbf5309_2    conda-forge
jinja2                    3.0.2              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jsoncpp                   1.9.4                h2d74725_3    conda-forge
jsonschema                4.1.2              pyhd8ed1ab_0    conda-forge
jupyter_client            7.0.6              pyhd8ed1ab_0    conda-forge
jupyter_core              4.8.1            py39hcbf5309_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
kaleido-core              0.2.1                h8ffe710_0    conda-forge
kiwisolver                1.3.2            py39h2e07f2f_0    conda-forge
krb5                      1.19.2               hbae68bd_2    conda-forge
latexcodec                2.0.1              pyh9f0ad1d_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge       
libcurl                   7.79.1               h789b8ee_1    conda-forge
libdeflate                1.8                  h8ffe710_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
liblapacke                3.9.0                     8_mkl    conda-forge
libnetcdf                 4.8.1           nompi_hf689e7d_100    conda-forge       
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtheora                 1.1.1             h8d14728_1005    conda-forge
libtiff                   4.3.0                hd413186_2    conda-forge
libuv                     1.42.0               h8ffe710_0    conda-forge
libxml2                   2.9.12               hf5bbc77_0    conda-forge
libzip                    1.8.0                hfed4ece_1    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
llvmlite                  0.36.0           py39ha0cd8c8_0    conda-forge
loguru                    0.5.3            py39hcbf5309_2    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge       
markupsafe                2.0.1            py39hb82d6ee_0    conda-forge
mathjax                   2.7.7                         0    conda-forge
matplotlib                3.4.3            py39hcbf5309_1    conda-forge
matplotlib-base           3.4.3            py39h581301d_1    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py39hb82d6ee_1004    conda-forge        
mkl                       2020.4             hb70f87d_311    conda-forge
mkl-devel                 2020.4             h57928b3_312    conda-forge
mkl-include               2020.4             hb70f87d_311    conda-forge
monty                     2021.8.17          pyhd8ed1ab_0    conda-forge
more-itertools            8.10.0             pyhd8ed1ab_0    conda-forge
mpmath                    1.2.1              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
mypy                      0.910            py39hb82d6ee_0    conda-forge
mypy_extensions           0.4.3            py39hcbf5309_3    conda-forge
nbclient                  0.5.4              pyhd8ed1ab_0    conda-forge
nbconvert                 6.2.0            py39hcbf5309_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
netcdf4                   1.5.7           nompi_py39ha89693b_101    conda-forge   
networkx                  2.5                        py_0    conda-forge
nodeenv                   1.6.0              pyhd8ed1ab_0    conda-forge
notebook                  6.4.5              pyha770c72_0    conda-forge
numba                     0.53.1           py39hb8cd55e_1    conda-forge
numpy                     1.21.3           py39h6635163_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1l               h8ffe710_0    conda-forge
packaging                 21.0               pyhd8ed1ab_0    conda-forge
palettable                3.3.0                      py_0    conda-forge
pandas                    1.3.4            py39h2e25243_0    conda-forge
pandoc                    2.14.2               h8ffe710_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.3.2            py39h916092e_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pipreqs                   0.4.10                     py_0    conda-forge
platformdirs              2.3.0              pyhd8ed1ab_0    conda-forge
plotly                    5.3.1              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0            py39hcbf5309_1    conda-forge
pqdm                      0.1.0                      py_0    sgbaird
pre-commit                2.15.0           py39hcbf5309_0    conda-forge
pre_commit                2.15.0               hd8ed1ab_0    conda-forge
progressbar2              3.53.1             pyh9f0ad1d_0    conda-forge
proj                      8.1.1                h1cfcee9_2    conda-forge
prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.21             pyha770c72_0    conda-forge
psutil                    5.8.0            py39hb82d6ee_1    conda-forge
pugixml                   1.11.4               h0e60522_0    conda-forge
py                        1.10.0             pyhd3deb0d_0    conda-forge
pybtex                    0.24.0           py39hcbf5309_0    conda-forge
pycodestyle               2.8.0              pyhd8ed1ab_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydocstyle                6.1.1              pyhd8ed1ab_0    conda-forge
pyflakes                  2.4.0              pyhd8ed1ab_0    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pymatgen                  2022.0.16        py39h2e07f2f_0    conda-forge
pynndescent               0.5.5              pyh6c4a22f_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py39hcbf5309_7    conda-forge
pyqt-impl                 5.12.3           py39h415ef7b_7    conda-forge
pyqt5-sip                 4.19.18          py39h415ef7b_7    conda-forge
pyqtchart                 5.12             py39h415ef7b_7    conda-forge
pyqtwebengine             5.12.1           py39h415ef7b_7    conda-forge
pyrsistent                0.17.3           py39hb82d6ee_2    conda-forge
pysocks                   1.7.1            py39hcbf5309_3    conda-forge
pytest                    6.2.5            py39hcbf5309_0    conda-forge
python                    3.9.7           h7840368_3_cpython    conda-forge       
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-kaleido            0.2.1              pyhd8ed1ab_0    conda-forge
python-utils              2.5.6              pyh44b312d_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.10.0          py3.9_cuda11.3_cudnn8_0    pytorch      
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pywin32                   301              py39hb82d6ee_0    conda-forge
pywinpty                  1.1.4            py39h99910a6_0    conda-forge
pyyaml                    6.0              py39hb82d6ee_0    conda-forge
pyzmq                     22.3.0           py39he46f08e_0    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
rapidfuzz                 1.8.1            py39h2e25243_0    conda-forge
regex                     2021.10.23       py39hb82d6ee_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.16          py39hb82d6ee_0    conda-forge
ruamel.yaml.clib          0.2.2            py39hb82d6ee_2    conda-forge
ruamel.yaml.jinja2        0.2.4                      py_1    conda-forge
scikit-learn              1.0              py39h74df8f2_1    conda-forge
scipy                     1.7.1            py39hc0c34ad_0    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                58.2.0           py39hcbf5309_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snowballstemmer           2.1.0              pyhd8ed1ab_0    conda-forge
spglib                    1.16.2           py39h5d4886f_0    conda-forge
sphinx                    4.2.0              pyh6c4a22f_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_0    conda-forge      
sqlite                    3.36.0               h8ffe710_2    conda-forge
statsmodels               0.13.0           py39h5d4886f_0    conda-forge
stdlib-list               0.7.0                      py_2    conda-forge
sympy                     1.9              py39hcbf5309_0    conda-forge
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
tbb                       2020.2               h2d74725_4    conda-forge
tbb-devel                 2020.2               h2d74725_4    conda-forge
tenacity                  8.0.1              pyhd8ed1ab_0    conda-forge
terminado                 0.12.1           py39hcbf5309_0    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.0.0              pyh8a188c0_0    conda-forge
tk                        8.6.11               h8ffe710_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     1.2.1              pyhd8ed1ab_0    conda-forge
tomli-w                   0.4.0              pyhd8ed1ab_0    conda-forge
tornado                   6.1              py39hb82d6ee_1    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.0              pyhd8ed1ab_0    conda-forge
typed-ast                 1.4.3            py39hb82d6ee_0    conda-forge
typing-extensions         3.10.0.2             hd8ed1ab_0    conda-forge
typing_extensions         3.10.0.2           pyha770c72_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
umap-learn                0.5.1            py39hcbf5309_1    conda-forge
uncertainties             3.1.6              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
utfcpp                    3.2.1                h57928b3_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
virtualenv                20.4.7           py39hcbf5309_0    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
vtk                       9.0.3           no_osmesa_py39h7e96c5d_105    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  2.0.1              pyhd8ed1ab_0    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
win32_setctime            1.0.3                      py_0    conda-forge
win_inet_pton             1.1.0            py39hcbf5309_2    conda-forge
winpty                    0.4.3                         4    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yarg                      0.1.9                      py_1    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
zstd                      1.5.0                h6255e5f_0    conda-forge
```
 - pip list
```python
(mat_discover) PS C:\Users\sterg\Documents\GitHub\sparks-baird\mat_discover> pip list
Package                       Version
----------------------------- ------------
alabaster                     0.7.12
appdirs                       1.4.4
argon2-cffi                   21.1.0
ase                           3.22.0
async-generator               1.10
atomicwrites                  1.4.0
attrs                         21.2.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
black                         21.9b0
bleach                        4.1.0
bounded-pool-executor         0.0.3
brotlipy                      0.7.0
certifi                       2021.10.8
cffi                          1.14.6
cfgv                          3.3.1
cftime                        1.5.1
chardet                       4.0.0
charset-normalizer            2.0.0
click                         8.0.3
colorama                      0.4.4
cryptography                  35.0.0
cycler                        0.10.0
Cython                        0.29.24
dataclasses                   0.8
debugpy                       1.4.1
decorator                     5.1.0
defusedxml                    0.7.1
dill                          0.3.4
distlib                       0.3.3
docopt                        0.6.2
docutils                      0.17.1
editdistance-s                1.0.0
ElM2D                         0.4.1
ElMD                          0.4.8
entrypoints                   0.3
filelock                      3.3.1
flake8                        4.0.1
Flask                         2.0.2
flit                          3.4.0
flit_core                     3.4.0
future                        0.18.2
grayskull                     0.9.1
hdbscan                       0.8.27
identify                      2.3.1
idna                          3.1
imagesize                     1.2.0
importlib-metadata            4.8.1
iniconfig                     1.1.1
ipykernel                     6.4.2
ipython                       7.28.0
ipython-genutils              0.2.0
itsdangerous                  2.0.1
jedi                          0.18.0
Jinja2                        3.0.2
joblib                        1.1.0
jsonschema                    4.1.2
jupyter-client                7.0.6
jupyter-core                  4.8.1
jupyterlab-pygments           0.1.2
kaleido                       0.2.1
kiwisolver                    1.3.2
latexcodec                    2.0.1
llvmlite                      0.36.0
loguru                        0.5.3
MarkupSafe                    2.0.1
matplotlib                    3.4.3
matplotlib-inline             0.1.3
mccabe                        0.6.1
mistune                       0.8.4
monty                         2021.8.17
more-itertools                8.10.0
mpmath                        1.2.1
mypy                          0.910
mypy-extensions               0.4.3
nbclient                      0.5.4
nbconvert                     6.2.0
nbformat                      5.1.3
nest-asyncio                  1.5.1
netCDF4                       1.5.7
networkx                      2.5
nodeenv                       1.6.0
notebook                      6.4.5
numba                         0.53.1
numpy                         1.21.3
olefile                       0.46
packaging                     21.0
palettable                    3.3.0
pandas                        1.3.4
pandocfilters                 1.5.0
parso                         0.8.2
pathspec                      0.9.0
patsy                         0.5.2
pickleshare                   0.7.5
Pillow                        8.3.2
pip                           21.3.1
pipreqs                       0.4.10
platformdirs                  2.3.0
plotly                        5.3.1
pluggy                        1.0.0
pqdm                          0.1.0
pre-commit                    2.15.0
progressbar2                  3.53.1
prometheus-client             0.11.0
prompt-toolkit                3.0.21
psutil                        5.8.0
py                            1.10.0
pybtex                        0.24.0
pycodestyle                   2.8.0
pycparser                     2.20
pydocstyle                    6.1.1
pyflakes                      2.4.0
Pygments                      2.10.0
pymatgen                      2022.0.16
pynndescent                   0.5.5
pyOpenSSL                     21.0.0
pyparsing                     2.4.7
PyQt5                         5.12.3
PyQt5_sip                     4.19.18
PyQtChart                     5.12
PyQtWebEngine                 5.12.1
pyrsistent                    0.17.3
PySocks                       1.7.1
pytest                        6.2.5
python-dateutil               2.8.2
python-utils                  2.5.6
pytz                          2021.3
pywin32                       301
pywinpty                      1.1.4
PyYAML                        6.0
pyzmq                         22.3.0
rapidfuzz                     1.8.1
regex                         2021.10.23
requests                      2.26.0
ruamel.yaml                   0.17.16
ruamel.yaml.clib              0.2.2
ruamel.yaml.jinja2            0.2.4
scikit-learn                  1.0
scipy                         1.7.1
seaborn                       0.11.2
Send2Trash                    1.8.0
setuptools                    58.2.0
six                           1.16.0
snowballstemmer               2.1.0
spglib                        1.16.2
Sphinx                        4.2.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
statsmodels                   0.13.0
stdlib-list                   0.7.0
sympy                         1.9
tabulate                      0.8.9
tenacity                      8.0.1
terminado                     0.12.1
testpath                      0.5.0
threadpoolctl                 3.0.0
toml                          0.10.2
tomli                         1.2.1
tomli_w                       0.4.0
torch                         1.10.0
tornado                       6.1
tqdm                          4.62.3
traitlets                     5.1.0
typed-ast                     1.4.3
typing-extensions             3.10.0.2
umap-learn                    0.5.1
uncertainties                 3.1.6
urllib3                       1.26.7
virtualenv                    20.4.7
vtk                           -PKG-VERSION
wcwidth                       0.2.5
webencodings                  0.5.1
Werkzeug                      2.0.1
wheel                         0.37.0
win-inet-pton                 1.1.0
win32-setctime                1.0.3
yarg                          0.1.9
zipp                          3.6.0
```
 - grayskull --version
```python
(mat_discover) PS C:\Users\sterg\Documents\GitHub\sparks-baird\mat_discover> grayskull --version
0.9.1
```
**Additional context**
#243 https://github.com/takluyver/flit/issues/461

**Comment by marcelotrevisani** [comment]
Closing this in favor of ``souschef``

**Comment by sgbaird** [comment]
Same issue seems to be surfacing when used with the `check-yaml` precommit hook.

```
check yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

while scanning for the next token
found character that cannot start any token
  in "src/xtal2png/meta.yaml", line 1, column 2
```

first two lines of `meta.yaml`:
```
{% set name = "xtal2png" %}
{% set version = "0.1.3" %}
```
