### ISSUE TITLE
[BUG] requirements with comments

### ISSUE THREAD

**Issue by woutdenolf** [conda-incubator/grayskull#358]
```
grayskull pypi ewoksjob --extras-require-test test
```

```
Traceback (most recent call last):
  File "/home/denolf/dev/grayskull/grayskull/strategy/pypi.py", line 435, in update_recipe
    recipe[section].update(metadata[section])
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/souschef/section.py", line 78, in update
    self[k] = val
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/souschef/mixins.py", line 196, in __setitem__
    self[key].append(i)
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/souschef/ingredient.py", line 117, in append
    self.insert(len(self), value)
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/souschef/mixins.py", line 272, in insert
    self.__add_comment_to_list(pos, value)
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/souschef/mixins.py", line 310, in __add_comment_to_list
    self[pos].inline_comment.value += f"{NEW_LINE}{value}"
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by marcelotrevisani** [comment]
Can you test with the latest grayskull please?

**Comment by marcelotrevisani** [comment]
Because with the latest grayskull I was able to generate
```yaml
{% set name = "ewoksjob" %}
{% set version = "0.0.9a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ewoksjob-{{ version }}.tar.gz
  sha256: cc03e9411cad52fe76fe1cbeff319775b645626da728461f6b781b70fbf283d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - celery
    - ewoksutils
    - python >=3.6

test:
  imports:
    - ewoksjob
  commands:
    - pip check
    - pytest --pyargs ewoksjob
  requires:
    - pip
    - ewoks
    - pytest-redis
    - celery[sqlalchemy]
    - pytest
    - celery[redis]
    - pytest-celery

about:
  home: https://gitlab.esrf.fr/workflow/ewoks/ewoksjob/
  summary: Asynchronous and distributed scheduling of Ewoks workflows from python
  dev_url: https://gitlab.esrf.fr/workflow/ewoks/ewoksjob/
  license: MIT
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - marcelotrevisani

```

**Comment by woutdenolf** [comment]
Sorry, my bad. I somehow had an old version in my env.
